version: '3.7'
services:
  # mysql
  mysql:
    platform: 'linux/amd64'
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/mysql:/var/lib/mysql      
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  # postgres    
  postgres:
    restart: always
    image: postgres
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 38080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  # redis
  redis:
    restart: always
    image: redis
    volumes:
      - ./db/redis/data:/data
    command: redis-server --appendonly yes      

  # mongo
  mongo:
    restart: always
    image: mongo
    volumes:
      - ./db/mongo/db:/data/db    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports: ["28080:80"]
    depends_on: ["mysql"]
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password

  php:
    #image: php:8.0-fpm
    build: ./php 
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ~/work/hgoe:/usr/share/nginx/now #今のプロジェクトについて✨
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["mysql","postgres","redis","mongo"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ~/work/hgoe:/usr/share/nginx/now #今のプロジェクトについて✨
    restart: always
    ports: ["18080:80","18081:81"]
    depends_on: ["php"]